# Generated by Django 4.2.11 on 2024-10-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
