SiteChoices = [
    ('My Network\\WEST\\ABQ-Station', 'ABQ-Station'),
    ('My Network\\WEST\\AeroData', 'AeroData'),
    ('My Network\\EAST\\ALB-Cargo', 'ALB-Cargo'),
    ('My Network\\EAST\\ALB-Station', 'ALB-Station'),
    ('My Network\\CENTRAL\\AMA-Station', 'AMA-Station'),
    ('My Network\\EAST\\ATL-MX', 'ATL-MX'),
    ('My Network\\EAST\\ATL-Station', 'ATL-Station'),
    ('My Network\\EAST\\ATL-Tech Services', 'ATL-Tech Services'),
    ('My Network\\EAST\\ATL-Warehouse', 'ATL-Warehouse'),
    ('My Network\\EAST\\AUA-Station', 'AUA-Station'),
    ('My Network\\CENTRAL\\AUS-Station', 'AUS-Station'),
    ('My Network\\CENTRAL\\AUS-SWAU', 'AUS-SWAU'),
    ('My Network\\EAST\\BDL-Cargo', 'BDL-Cargo'),
    ('My Network\\EAST\\BDL-Station', 'BDL-Station'),
    ('My Network\\CENTRAL\\BHM-Cargo', 'BHM-Cargo'),
    ('My Network\\CENTRAL\\BHM-Station', 'BHM-Station'),
    ('My Network\\EAST\\BNA-GUB', 'BNA-GUB'),
    ('My Network\\EAST\\BNA-Station', 'BNA-Station'),
    ('My Network\\EAST\\BNA-SWAU', 'BNA-SWAU'),
    ('My Network\\WEST\\BOI-Cargo', 'BOI-Cargo'),
    ('My Network\\WEST\\BOI-Station', 'BOI-Station'),
    ('My Network\\EAST\\BOS-Cargo', 'BOS-Cargo'),
    ('My Network\\EAST\\BOS-Station', 'BOS-Station'),
    ('My Network\\EAST\\BUF-Cargo', 'BUF-Cargo'),
    ('My Network\\EAST\\BUF-Station', 'BUF-Station'),
    ('My Network\\WEST\\BUR-Cargo', 'BUR-Cargo'),
    ('My Network\\WEST\\BUR-Station', 'BUR-Station'),
    ('My Network\\EAST\\BWI-Station', 'BWI-Station'),
    ('My Network\\CENTRAL\\BZE-Cargo', 'BZE-Cargo'),
    ('My Network\\CENTRAL\\BZE-Station', 'BZE-Station'),
    ('My Network\\WEST\\BZN-Station', 'BZN-Station'),
    ('My Network\\EAST\\CHS-Cargo', 'CHS-Cargo'),
    ('My Network\\EAST\\CHS-Station', 'CHS-Station'),
    ('My Network\\CENTRAL\\CLE-Cargo', 'CLE-Cargo'),
    ('My Network\\CENTRAL\\CLE-Station', 'CLE-Station'),
    ('My Network\\EAST\\CLT-Cargo', 'CLT-Cargo'),
    ('My Network\\EAST\\CLT-Station', 'CLT-Station'),
    ('My Network\\CENTRAL\\CMH-Cargo', 'CMH-Cargo'),
    ('My Network\\CENTRAL\\CMH-Station', 'CMH-Station'),
    ('My Network\\Data Center\\Comm Hub 1', 'Comm Hub 1'),
    ('My Network\\Data Center\\Comm Hub 2', 'Comm Hub 2'),
    ('My Network\\WEST\\COS-Station', 'COS-Station'),
    ('My Network\\CENTRAL\\CRC', 'CRC'),
    ('My Network\\CENTRAL\\CRP-Cargo', 'CRP-Cargo'),
    ('My Network\\CENTRAL\\CRP-Station', 'CRP-Station'),
    ('My Network\\CENTRAL\\CUN-Cargo', 'CUN-Cargo'),
    ('My Network\\CENTRAL\\CUN-Station', 'CUN-Station'),
    ('My Network\\CENTRAL\\CVG-Cargo', 'CVG-Cargo'),
    ('My Network\\CENTRAL\\CVG-Station', 'CVG-Station'),
    ('My Network\\CENTRAL\\DAL-MX', 'DAL-MX'),
    ('My Network\\CENTRAL\\DAL-Station', 'DAL-Station'),
    ('My Network\\CENTRAL\\DAL-TECH', 'DAL-TECH'),
    ('My Network\\EAST\\DCA-Station', 'DCA-Station'),
    ('My Network\\WEST\\DEN-MX', 'DEN-MX'),
    ('My Network\\WEST\\DEN-Station', 'DEN-Station'),
    ('My Network\\CENTRAL\\DSM-Station', 'DSM-Station'),
    ('My Network\\CENTRAL\\DTW-Cargo', 'DTW-Cargo'),
    ('My Network\\CENTRAL\\DTW-Station', 'DTW-Station'),
    ('My Network\\EAST\\ECP-Station', 'ECP-Station'),
    ('My Network\\CENTRAL\\ELP-Cargo', 'ELP-Cargo'),
    ('My Network\\CENTRAL\\ELP-Station', 'ELP-Station'),
    ('My Network\\Data Center\\Erding', 'Erding'),
    ('My Network\\Data Center\\EU-CH1', 'EU-CH1'),
    ('My Network\\Data Center\\EU-CH2', 'EU-CH2'),
    ('My Network\\WEST\\EUG-Station', 'EUG-Station'),
    ('My Network\\WEST\\FAT-Station', 'FAT-Station'),
    ('My Network\\EAST\\FLL-Cargo', 'FLL-Cargo'),
    ('My Network\\EAST\\FLL-Provo', 'FLL-Provo'),
    ('My Network\\EAST\\FLL-Station', 'FLL-Station'),
    ('My Network\\Campus\\FTC_WINGS\\FTC LEAD Building', 'FTC_WINGS\\FTC LEAD Building'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-0 Floor', 'FTC_WINGS\\FTC-0 Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-1st Floor', 'FTC_WINGS\\FTC-1st Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-2nd Floor', 'FTC_WINGS\\FTC-2nd Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-3rd Floor', 'FTC_WINGS\\FTC-3rd Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-4th Floor', 'FTC_WINGS\\FTC-4th Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-5th Floor', 'FTC_WINGS\\FTC-5th Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-6th Floor', 'FTC_WINGS\\FTC-6th Floor'),
    ('My Network\\Campus\\FTC_WINGS\\FTC-Core', 'FTC_WINGS\\FTC-Core'),
    ('My Network\\Campus\\FTC_WINGS\\MKE Ticket Counter Room 24', 'FTC_WINGS\\MKE Ticket Counter Room 24'),
    ('My Network\\EAST\\GCM-Station', 'GCM-Station'),
    ('My Network\\WEST\\GEG-Cargo', 'GEG-Cargo'),
    ('My Network\\WEST\\GEG-Station', 'GEG-Station'),
    ('My Network\\EAST\\GRC', 'GRC'),
    ('My Network\\CENTRAL\\GRR-Cargo', 'GRR-Cargo'),
    ('My Network\\CENTRAL\\GRR-Station', 'GRR-Station'),
    ('My Network\\EAST\\GSO-MX', 'GSO-MX'),
    ('My Network\\EAST\\GSP-Cargo', 'GSP-Cargo'),
    ('My Network\\EAST\\GSP-Station', 'GSP-Station'),
    ('My Network\\EAST\\HAV-Station', 'HAV-Station'),
    ('My Network\\WEST\\HDN-Station', 'HDN-Station'),
    ('My Network\\Campus\\HDQ\\Guard Shack', 'HDQ\\Guard Shack'),
    ('My Network\\Campus\\HDQ\\HDQ Other', 'HDQ\\HDQ Other'),
    ('My Network\\Campus\\HDQ\\HDQ-1st Floor', 'HDQ\\HDQ-1st Floor'),
    ('My Network\\Campus\\HDQ\\HDQ-2nd Floor', 'HDQ\\HDQ-2nd Floor'),
    ('My Network\\Campus\\HDQ\\HDQ-3rd Floor', 'HDQ\\HDQ-3rd Floor'),
    ('My Network\\Campus\\HDQ\\HDQ-4th Floor', 'HDQ\\HDQ-4th Floor'),
    ('My Network\\Campus\\HDQ\\HDQ-5th Floor', 'HDQ\\HDQ-5th Floor'),
    ('My Network\\Campus\\HDQ\\HDQ-Core', 'HDQ\\HDQ-Core'),
    ('My Network\\Campus\\HDQ\\HDQ-FSO', 'HDQ\\HDQ-FSO'),
    ('My Network\\Campus\\HDQ\\SIM Bldg', 'HDQ\\SIM Bldg'),
    ('My Network\\WEST\\HNL-MX', 'HNL-MX'),
    ('My Network\\WEST\\HNL-Provo', 'HNL-Provo'),
    ('My Network\\WEST\\HNL-Station', 'HNL-Station'),
    ('My Network\\CENTRAL\\HOU-MX', 'HOU-MX'),
    ('My Network\\CENTRAL\\HOU-Station', 'HOU-Station'),
    ('My Network\\Campus\\HQA', 'HQA'),
    ('My Network\\CENTRAL\\HRL-Cargo', 'HRL-Cargo'),
    ('My Network\\CENTRAL\\HRL-Station', 'HRL-Station'),
    ('My Network\\EAST\\IAD-Cargo', 'IAD-Cargo'),
    ('My Network\\EAST\\IAD-Station', 'IAD-Station'),
    ('My Network\\CENTRAL\\ICT-Station', 'ICT-Station'),
    ('My Network\\CENTRAL\\IND-Cargo', 'IND-Cargo'),
    ('My Network\\CENTRAL\\IND-MX', 'IND-MX'),
    ('My Network\\CENTRAL\\IND-Station', 'IND-Station'),
    ('My Network\\EAST\\ISP-Cargo', 'ISP-Cargo'),
    ('My Network\\EAST\\ISP-Station', 'ISP-Station'),
    ('My Network\\WEST\\ITO-Station', 'ITO-Station'),
    ('My Network\\CENTRAL\\JAN-Cargo', 'JAN-Cargo'),
    ('My Network\\CENTRAL\\JAN-Station', 'JAN-Station'),
    ('My Network\\EAST\\JAX-Cargo', 'JAX-Cargo'),
    ('My Network\\EAST\\JAX-Station', 'JAX-Station'),
    ('My Network\\WEST\\KOA-Cargo', 'KOA-Cargo'),
    ('My Network\\WEST\\KOA-Station', 'KOA-Station'),
    ('My Network\\WEST\\LAS-Station', 'LAS-Station'),
    ('My Network\\WEST\\LAX-Cargo', 'LAX-Cargo'),
    ('My Network\\WEST\\LAX-Provo', 'LAX-Provo'),
    ('My Network\\WEST\\LAX-Station', 'LAX-Station'),
    ('My Network\\CENTRAL\\LBB-Station', 'LBB-Station'),
    ('My Network\\EAST\\LGA-Cargo', 'LGA-Cargo'),
    ('My Network\\EAST\\LGA-Station', 'LGA-Station'),
    ('My Network\\WEST\\LGB-Station', 'LGB-Station'),
    ('My Network\\WEST\\LIH-Cargo', 'LIH-Cargo'),
    ('My Network\\WEST\\LIH-Station', 'LIH-Station'),
    ('My Network\\CENTRAL\\LIR-Cargo', 'LIR-Cargo'),
    ('My Network\\CENTRAL\\LIR-Station', 'LIR-Station'),
    ('My Network\\CENTRAL\\LIT-Cargo', 'LIT-Cargo'),
    ('My Network\\CENTRAL\\LIT-Station', 'LIT-Station'),
    ('My Network\\CENTRAL\\MAF-Cargo', 'MAF-Cargo'),
    ('My Network\\CENTRAL\\MAF-Station', 'MAF-Station'),
    ('My Network\\EAST\\MBJ-Cargo', 'MBJ-Cargo'),
    ('My Network\\EAST\\MBJ-Station', 'MBJ-Station'),
    ('My Network\\CENTRAL\\MCI-Cargo-Provo', 'MCI-Cargo-Provo'),
    ('My Network\\CENTRAL\\MCI-MX', 'MCI-MX'),
    ('My Network\\CENTRAL\\MCI-Station', 'MCI-Station'),
    ('My Network\\EAST\\MCO-HR', 'MCO-HR'),
    ('My Network\\EAST\\MCO-MX', 'MCO-MX'),
    ('My Network\\EAST\\MCO-Station', 'MCO-Station'),
    ('My Network\\CENTRAL\\MDW-Cargo', 'MDW-Cargo'),
    ('My Network\\CENTRAL\\MDW-HR', 'MDW-HR'),
    ('My Network\\CENTRAL\\MDW-MX', 'MDW-MX'),
    ('My Network\\CENTRAL\\MDW-Station', 'MDW-Station'),
    ('My Network\\CENTRAL\\MDW-SWAU', 'MDW-SWAU'),
    ('My Network\\CENTRAL\\MEM-Cargo', 'MEM-Cargo'),
    ('My Network\\CENTRAL\\MEM-Station', 'MEM-Station'),
    ('My Network\\EAST\\MHT-Cargo', 'MHT-Cargo'),
    ('My Network\\EAST\\MHT-Station', 'MHT-Station'),
    ('My Network\\EAST\\MIA-Cargo', 'MIA-Cargo'),
    ('My Network\\EAST\\MIA-MX', 'MIA-MX'),
    ('My Network\\EAST\\MIA-Station', 'MIA-Station'),
    ('My Network\\CENTRAL\\MKE-Cargo', 'MKE-Cargo'),
    ('My Network\\CENTRAL\\MKE-Station', 'MKE-Station'),
    ('My Network\\CENTRAL\\MSP-Cargo', 'MSP-Cargo'),
    ('My Network\\CENTRAL\\MSP-Station', 'MSP-Station'),
    ('My Network\\CENTRAL\\MSY-Cargo', 'MSY-Cargo'),
    ('My Network\\CENTRAL\\MSY-Station', 'MSY-Station'),
    ('My Network\\WEST\\MTJ-Station', 'MTJ-Station'),
    ('My Network\\Data Center\\Munich', 'Munich'),
    ('My Network\\EAST\\MYR-Station', 'MYR-Station'),
    ('My Network\\EAST\\NAS-Station', 'NAS-Station'),
    ('My Network\\WEST\\OAK-gse', 'OAK-gse'),
    ('My Network\\WEST\\OAK-Provo', 'OAK-Provo'),
    ('My Network\\WEST\\OAK-Station', 'OAK-Station'),
    ('My Network\\WEST\\OGG-Cargo', 'OGG-Cargo'),
    ('My Network\\WEST\\OGG-Station', 'OGG-Station'),
    ('My Network\\CENTRAL\\OKC-Cargo', 'OKC-Cargo'),
    ('My Network\\CENTRAL\\OKC-Station', 'OKC-Station'),
    ('My Network\\CENTRAL\\OMA-Cargo', 'OMA-Cargo'),
    ('My Network\\CENTRAL\\OMA-Station', 'OMA-Station'),
    ('My Network\\WEST\\ONT-Station', 'ONT-Station'),
    ('My Network\\CENTRAL\\ORD-Cargo', 'ORD-Cargo'),
    ('My Network\\CENTRAL\\ORD-Station', 'ORD-Station'),
    ('My Network\\EAST\\ORF-Cargo', 'ORF-Cargo'),
    ('My Network\\EAST\\ORF-Station', 'ORF-Station'),
    ('My Network\\WEST\\PAE-MX', 'PAE-MX'),
    ('My Network\\EAST\\PBI-Cargo', 'PBI-Cargo'),
    ('My Network\\EAST\\PBI-Station', 'PBI-Station'),
    ('My Network\\Campus\\PDC\\PDC Amadeus', 'PDC\\PDC Amadeus'),
    ('My Network\\Campus\\PDC\\PDC B2B BIZ', 'PDC\\PDC B2B BIZ'),
    ('My Network\\Campus\\PDC\\PDC Lab', 'PDC\\PDC Lab'),
    ('My Network\\Campus\\PDC\\PDC Other', 'PDC\\PDC Other'),
    ('My Network\\WEST\\PDX-Cargo', 'PDX-Cargo'),
    ('My Network\\WEST\\PDX-Station', 'PDX-Station'),
    ('My Network\\EAST\\PHL-Station', 'PHL-Station'),
    ('My Network\\WEST\\PHX-MX', 'PHX-MX'),
    ('My Network\\WEST\\PHX-Station', 'PHX-Station'),
    ('My Network\\EAST\\PIT-Cargo', 'PIT-Cargo'),
    ('My Network\\EAST\\PIT-Station', 'PIT-Station'),
    ('My Network\\EAST\\PLS-Station', 'PLS-Station'),
    ('My Network\\EAST\\PNS-Station', 'PNS-Station'),
    ('My Network\\WEST\\PSP-Station', 'PSP-Station'),
    ('My Network\\EAST\\PUJ-Station', 'PUJ-Station'),
    ('My Network\\EAST\\PVD-Cargo', 'PVD-Cargo'),
    ('My Network\\EAST\\PVD-Station', 'PVD-Station'),
    ('My Network\\CENTRAL\\PVR-Station', 'PVR-Station'),
    ('My Network\\EAST\\PWM-Station', 'PWM-Station'),
    ('My Network\\EAST\\RDU-Cargo', 'RDU-Cargo'),
    ('My Network\\EAST\\RDU-Station', 'RDU-Station'),
    ('My Network\\EAST\\RIC-Cargo', 'RIC-Cargo'),
    ('My Network\\EAST\\RIC-Station', 'RIC-Station'),
    ('My Network\\WEST\\RNO-Cargo', 'RNO-Cargo'),
    ('My Network\\WEST\\RNO-Station', 'RNO-Station'),
    ('My Network\\EAST\\ROC-Station', 'ROC-Station'),
    ('My Network\\CENTRAL\\ROK-Station', 'ROK-Station'),
    ('My Network\\EAST\\RSW-Cargo', 'RSW-Cargo'),
    ('My Network\\EAST\\RSW-Station', 'RSW-Station'),
    ('My Network\\CENTRAL\\SAL-MX', 'SAL-MX'),
    ('My Network\\WEST\\SAN-Station', 'SAN-Station'),
    ('My Network\\CENTRAL\\SAT-Cargo', 'SAT-Cargo'),
    ('My Network\\CENTRAL\\SAT-Station', 'SAT-Station'),
    ('My Network\\EAST\\SAV-Station', 'SAV-Station'),
    ('My Network\\WEST\\SBA-Station', 'SBA-Station'),
    ('My Network\\Data Center\\SDC\\Amadeus', 'SDC\\Amadeus'),
    ('My Network\\Data Center\\SDC\\B2B', 'SDC\\B2B'),
    ('My Network\\Data Center\\SDC\\Core', 'SDC\\Core'),
    ('My Network\\Data Center\\SDC\\DEV', 'SDC\\DEV'),
    ('My Network\\Data Center\\SDC\\ECOM', 'SDC\\ECOM'),
    ('My Network\\Data Center\\SDC\\NAS', 'SDC\\NAS'),
    ('My Network\\Data Center\\SDC\\SDC Other', 'SDC\\SDC Other'),
    ('My Network\\CENTRAL\\SDF-Cargo', 'SDF-Cargo'),
    ('My Network\\CENTRAL\\SDF-Station', 'SDF-Station'),
    ('My Network\\WEST\\SEA-Cargo', 'SEA-Cargo'),
    ('My Network\\WEST\\SEA-Station', 'SEA-Station'),
    ('My Network\\WEST\\SFO-Cargo', 'SFO-Cargo'),
    ('My Network\\WEST\\SFO-Station', 'SFO-Station'),
    ('My Network\\WEST\\SJC-Cargo', 'SJC-Cargo'),
    ('My Network\\WEST\\SJC-Station', 'SJC-Station'),
    ('My Network\\CENTRAL\\SJD-Station', 'SJD-Station'),
    ('My Network\\CENTRAL\\SJO-Cargo', 'SJO-Cargo'),
    ('My Network\\CENTRAL\\SJO-Station', 'SJO-Station'),
    ('My Network\\EAST\\SJU-Cargo', 'SJU-Cargo'),
    ('My Network\\EAST\\SJU-Station', 'SJU-Station'),
    ('My Network\\WEST\\SLC-Station', 'SLC-Station'),
    ('My Network\\WEST\\SMF-Station', 'SMF-Station'),
    ('My Network\\WEST\\SNA-Cargo', 'SNA-Cargo'),
    ('My Network\\WEST\\SNA-Station', 'SNA-Station'),
    ('My Network\\EAST\\SRQ-Station', 'SRQ-Station'),
    ('My Network\\CENTRAL\\STL-Provo', 'STL-Provo'),
    ('My Network\\CENTRAL\\STL-Station', 'STL-Station'),
    ('My Network\\Campus\\TOPS\\TOPS-1st Floor', 'TOPS\\TOPS-1st Floor'),
    ('My Network\\Campus\\TOPS\\TOPS-2nd Floor', 'TOPS\\TOPS-2nd Floor'),
    ('My Network\\Campus\\TOPS\\TOPS-3rd Floor', 'TOPS\\TOPS-3rd Floor'),
    ('My Network\\Campus\\TOPS\\TOPS-4th Floor', 'TOPS\\TOPS-4th Floor'),
    ('My Network\\Campus\\TOPS\\TOPS-Core', 'TOPS\\TOPS-Core'),
    ('My Network\\EAST\\TPA-GSE', 'TPA-GSE'),
    ('My Network\\EAST\\TPA-Provo', 'TPA-Provo'),
    ('My Network\\EAST\\TPA-Station', 'TPA-Station'),
    ('My Network\\Campus\\TSB', 'TSB'),
    ('My Network\\CENTRAL\\TUL-Cargo', 'TUL-Cargo'),
    ('My Network\\CENTRAL\\TUL-Station', 'TUL-Station'),
    ('My Network\\WEST\\TUS-Cargo', 'TUS-Cargo'),
    ('My Network\\WEST\\TUS-Station', 'TUS-Station'),
    ('My Network\\EAST\\VPS-Station', 'VPS-Station'),
    ('My Network\\EAST\\WGA', 'WGA'),
    ('My Network\\Data Center\\WNDC', 'WNDC')
]