# Generated by Django 4.2.11 on 2024-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('mgmt_ip', models.GenericIPAddressField(null=True, protocol='IPv4', unique=True)),
                ('mgmt_interface', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('sysobjectid', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('software_version', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
            ],
        ),
    ]
